CREATE TABLE IF NOT EXISTS words (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Russian TEXT NOT NULL,
  English TEXT NOT NULL,
  Latin TEXT NOT NULL,
  parts TEXT NOT NULL  -- Store parts as JSON string
);